In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('foo.csv')

In [3]:
df.head(6)

foo bar  count
0    1   a      1
1    1  b       2
2    1   c      3
3    2   a      4
4    2  b       5
5    2   c      6

In [4]:
from sklearn.cross_validation import train_test_split

/home/alejandro/anaconda3/envs/beer/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
train, test = train_test_split(df)

In [6]:
train.shape

(29, 3)

In [7]:
test.shape

(10, 3)

In [8]:
def pivotarray(df):
    users,i= np.unique(df['foo'],return_inverse=True)
    item,j= np.unique(df['bar'],return_inverse=True)
    a=np.zeros((len(users),len(item)))
    a[i,j]=df['count']
    return a

In [9]:
ratings_train = pivotarray(train)
ratings_train

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 4.,  5.,  6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  6.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,
         0.],
       [ 9.,  0.,  0.,  2.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  1.,  0.,
         0.],
       [ 0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  6.,  0.,  3.,  0.,  0.,  5.,  6.,  0.,  9.,
         0.],
       [ 8.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  0.,  4.,  0.,  6.,  0.,
         0.],
       [ 0.,  0.,  0.,  7.,  0.,  0.,  0.,  0.,  0.,  0.,  5.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  6.,  0.,
         7.],
       [ 4.,  0.,  0.,  0.,  0.,  0.,  0., 

In [10]:
ratings_test = pivotarray(test)
ratings_test

array([[ 2.,  3.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  5.],
       [ 4.,  0.,  0.,  7.,  0.],
       [ 0.,  0.,  0.,  0.,  8.],
       [ 0.,  0.,  8.,  0.,  0.],
       [ 9.,  4.,  0.,  0.,  0.],
       [ 8.,  0.,  0.,  0.,  0.]])

In [11]:
import sklearn

In [12]:
from sklearn.neighbors import NearestNeighbors

In [13]:
k = 5
neigh = NearestNeighbors (k, 'cosine')
neigh.fit(ratings_train)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius='cosine')

In [14]:
top_k_distances, top_k_users = neigh.kneighbors (ratings_train, return_distance=True)

In [17]:
top_k_distances[0]

array([ 0.        ,  1.        ,  4.12310563,  5.09901951,  7.28010989])

In [18]:
np.array([np.abs(top_k_distances[0].T).sum(axis=0)])

array([ 17.50223503])

In [19]:
np.abs(top_k_distances[0].T)

array([ 0.        ,  1.        ,  4.12310563,  5.09901951,  7.28010989])

In [20]:
np.array([np.abs(top_k_distances[0].T).sum(axis=0)]).T

array([ 17.50223503])

In [21]:
top_k_distances[0].T.dot(ratings_train[top_k_users][0]) 

array([  2.        ,   0.        ,  16.4924225 ,  25.49509757,
         0.        ,  43.68065934,   0.        ,   0.        ,
        29.12043956,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ])

In [15]:
user_pred_values = np.zeros(ratings_train.shape)

for i in range(ratings_train.shape[0]): 
    user_pred_values[i] =   top_k_distances[i].T.dot(ratings_train[top_k_users][i]) 
/ np.array([np.abs(top_k_distances[i].T).sum(axis=0)]).T

AttributeError: 'list' object has no attribute 'T'

In [16]:
user_pred_k = np.zeros(ratings_train.shape) 

for i in range(ratings_train.shape[0]): 
    user_pred_k[i,:] =   top_k_distances[i].T.dot(ratings_train[top_k_users][i]) 
/ np.array([np.abs(top_k_distances[i].T).sum(axis=0)]).T



AttributeError: 'list' object has no attribute 'T'

In [24]:
user_pred_k.shape

(13, 13)