In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv ('beer_prueba1.csv')


In [3]:
df.head()

Unnamed: 0 profile_name  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1  \
0           0          007        985797          985797          985797   
1           1          007       1539730         1539730         1539730   
2           2          007       1544437         1544437         1544437   
3           3          007       1545868         1545868         1545868   
4           4          007       1549890         1549890         1549890   

                 names     Id  brewerId  ABV  \
0   Fraoch Heather Ale    245     12142  5.0   
1       Saison Du BUFF  61351       345  6.8   
2         HopDevil Ale   1005       345  6.7   
3   Helios  (V Saison)  47776       345  7.5   
4        Victory Lager   1002       345  4.8   

                                  style  ...   aroma  palate  taste  overall  \
0   Scottish Gruit / Ancient Herbed Ale  ...     2.5     3.5    4.0      4.5   
1                Saison / Farmhouse Ale  ...     3.5     4.5    3.5      4.5   
2                          American IPA  ...     5.0     4.5    5.0      5.0   
3                Saison / Farmhouse Ale  ...     3.5     3.5    4.0      4.0   
4                   Munich Helles Lager  ...     3.5     3.5    4.0      4.0   

         time                                               text       time2  \
0  1220542724  " First tried this as part of a mix case sever...  2008-09-04   
1  1285854092  " Poured from bottle into pint glass. \t\tHazy...  2010-09-30   
2  1286891828  " A- dark amber, lasting head, delicate epheme...  2010-10-12   
3  1291840287  " A. Hazy orange, little head retention but ni...  2010-12-08   
4  1288210632  " Victory Lager was my introduction to craft b...  2010-10-27   

  day  month  year  
0   4      9  2008  
1  30      9  2010  
2  12     10  2010  
3   8     12  2010  
4  27     10  2010  

[5 rows x 21 columns]

In [4]:
df = df.drop (df.columns[[0, 2, 3, 4, 15]], axis=1)
df.head()

profile_name                names     Id  brewerId  ABV  \
0          007   Fraoch Heather Ale    245     12142  5.0   
1          007       Saison Du BUFF  61351       345  6.8   
2          007         HopDevil Ale   1005       345  6.7   
3          007   Helios  (V Saison)  47776       345  7.5   
4          007        Victory Lager   1002       345  4.8   

                                  style  appearance  aroma  palate  taste  \
0   Scottish Gruit / Ancient Herbed Ale         3.5    2.5     3.5    4.0   
1                Saison / Farmhouse Ale         4.0    3.5     4.5    3.5   
2                          American IPA         4.5    5.0     4.5    5.0   
3                Saison / Farmhouse Ale         4.0    3.5     3.5    4.0   
4                   Munich Helles Lager         3.0    3.5     3.5    4.0   

   overall                                               text       time2  \
0      4.5  " First tried this as part of a mix case sever...  2008-09-04   
1      4.5  " Poured from bottle into pint glass. \t\tHazy...  2010-09-30   
2      5.0  " A- dark amber, lasting head, delicate epheme...  2010-10-12   
3      4.0  " A. Hazy orange, little head retention but ni...  2010-12-08   
4      4.0  " Victory Lager was my introduction to craft b...  2010-10-27   

   day  month  year  
0    4      9  2008  
1   30      9  2010  
2   12     10  2010  
3    8     12  2010  
4   27     10  2010

In [5]:
from sklearn import preprocessing

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
df['user_id'] = LabelEncoder().fit_transform(df.profile_name)

https://stackoverflow.com/questions/35869175/how-to-aggregate-the-values-of-a-dataframe-and-output-a-numpy-array-quickly

In [70]:
df.head(10)

profile_name                  names     Id  brewerId  ABV  \
0          007     Fraoch Heather Ale    245     12142  5.0   
1          007         Saison Du BUFF  61351       345  6.8   
2          007           HopDevil Ale   1005       345  6.7   
3          007     Helios  (V Saison)  47776       345  7.5   
4          007          Victory Lager   1002       345  4.8   
5        00766          Aphrodisiaque  10330      1141  6.5   
6        00766   Imperial Pumpkin Ale  25880       392  8.0   
7     01001111   Lips Of Faith - Kick  71919       192  8.5   
8     01001111      Reserve Wheat Ale  48084     13065  5.0   
9     01001111         CoCoNut Porter  37795     16057  6.0   

                                  style  appearance  aroma  palate  taste  \
0   Scottish Gruit / Ancient Herbed Ale         3.5    2.5     3.5    4.0   
1                Saison / Farmhouse Ale         4.0    3.5     4.5    3.5   
2                          American IPA         4.5    5.0     4.5    5.0   
3                Saison / Farmhouse Ale         4.0    3.5     3.5    4.0   
4                   Munich Helles Lager         3.0    3.5     3.5    4.0   
5                        American Stout         4.5    4.5     4.0    4.0   
6                           Pumpkin Ale         4.5    4.5     4.5    5.0   
7                Fruit / Vegetable Beer         3.0    2.5     2.5    3.0   
8                    Berliner Weissbier         4.5    4.0     4.5    4.5   
9                       American Porter         4.0    4.5     4.5    4.5   

   overall                                               text       time2  \
0      4.5  " First tried this as part of a mix case sever...  2008-09-04   
1      4.5  " Poured from bottle into pint glass. \t\tHazy...  2010-09-30   
2      5.0  " A- dark amber, lasting head, delicate epheme...  2010-10-12   
3      4.0  " A. Hazy orange, little head retention but ni...  2010-12-08   
4      4.0  " Victory Lager was my introduction to craft b...  2010-10-27   
5      4.0   Poured cool but for small head. Nice tan head...  2011-10-23   
6      4.5  " A Nice beer with subtle spicing. It is not t...  2011-10-11   
7      3.0   A, Pale amber.\t\tS," The smell is quite subt...  2012-01-02   
8      4.5   A," Golden straw, hazy white grape juice.\t\t...  2012-01-10   
9      4.5   A," A deep, dark chocolate brown.\t\tS", The ...  2011-12-28   

   day  month  year  user_id  
0    4      9  2008        0  
1   30      9  2010        0  
2   12     10  2010        0  
3    8     12  2010        0  
4   27     10  2010        0  
5   23     10  2011        1  
6   11     10  2011        1  
7    2      1  2012        2  
8   10      1  2012        2  
9   28     12  2011        2

In [8]:
df_most = df[df.overall>=4.0]

In [9]:
df_most.shape

(989514, 17)

In [10]:
df_ratings = df_most[['user_id', 'Id', 'overall']].copy()

In [11]:
df_ratings.sample(5)

user_id     Id  overall
910680     16719  58380      4.0
355109      6315  27107      4.5
1235694    23869  20678      4.5
803612     14423  67480      4.5
331691      5930    695      4.0

In [71]:
df_ratings.to_csv('ratings.csv')

In [77]:
df_days = df_most[['user_id', 'Id', 'day']].copy()

In [78]:
df_days.to_csv('days.csv')

In [12]:
users = df_ratings.user_id.unique().shape[0]
items = df_ratings.Id.unique().shape[0]
print("There are %s users and %s Id's" %(users, items))

There are 27717 users and 48936 Id's


In [13]:
ratings = np.zeros((users,items))

ratings

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [43]:
array = df_ratings.values
array

array([[  0.00000000e+00,   2.45000000e+02,   4.50000000e+00],
       [  0.00000000e+00,   6.13510000e+04,   4.50000000e+00],
       [  0.00000000e+00,   1.00500000e+03,   5.00000000e+00],
       ..., 
       [  3.06720000e+04,   1.41000000e+02,   4.50000000e+00],
       [  3.06720000e+04,   2.86870000e+04,   4.00000000e+00],
       [  3.06730000e+04,   2.27000000e+03,   5.00000000e+00]])

In [44]:
def fill(df_ratings):
     for row in array:
        ratings[row[0], row[1]] = df_ratings['overall']
        return ratings

In [45]:
fill(df_ratings)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [50]:
sample = df_ratings.sample(100)
sample.head()

user_id     Id  overall
1453315    28434    576      4.5
848810     15392  39296      4.5
674077     12076   2464      4.0
1303610    25039  13726      4.0
1435284    28048  32228      4.0

In [48]:
users_s = sample.user_id.unique().shape[0]
items_s = sample.Id.unique().shape[0]
print("There are %s users and %s Id's" %(users_s, items_s))

There are 98 users and 96 Id's


In [49]:
ratings_s = np.zeros((users_s,items_s))

ratings_s

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [56]:
def pivotarray(sample):
    users,i= np.unique(sample['user_id'],return_inverse=True)
    item,j= np.unique(sample['Id'],return_inverse=True)
    b= np.zeros((len(users),len(item)), float)
    b[i,j]= sample['overall']
    return b

In [57]:
pivotarray(sample)[1:50]

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [61]:
for row in sample.iterrows():
    ratings_s[row[1], row[2]] = row[3]

IndexError: tuple index out of range

In [ ]:
def pivotarray(df_ratings):
    users,i= np.unique(df_ratings['user_id'],return_inverse=True)
    item,j= np.unique(df_ratings['Id'],return_inverse=True)
    b=np.zeros((len(users),len(item)))
    b[i,j]=df_ratings['overall']
    return b


In [ ]:
pivotarray(df_ratings)